import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import "@/styles/index.scss";
import AOSProvider from "@/util/aos";
import Script from "next/script";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <link rel="icon" href="/assets/icon/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;500;600;700;900&family=Kanit:wght@400;500;600;700&display=swap"
        />
        <title>Shine Ngo - Best NGO in Gorakhpur</title>
      </head>

      <body>
        <AOSProvider>{children}</AOSProvider>
      </body>
      
      <Script src="/assets/js/jquery.min.js"></Script>
      <Script src="/assets/js/bootstrap.bundle.js"></Script>
      <Script src="/assets/js/jquery.meanmenu.js"></Script>
      <Script src="/assets/js/owl.carousel.min.js"></Script>
      <Script src="/assets/js/jquery.magnific-popup.min.js"></Script>
      <Script src="/assets/js/wow.min.js"></Script>
      <Script src="/assets/js/waypoints.min.js"></Script>
      <Script src="/assets/js/jquery.counterup.min.js"></Script>
      <Script src="/assets/js/custom.js"></Script>
      <Script src="/assets/js/gallery-popup.js"></Script>
    </html>
  );
}
